version: '3'
services:
  web:
    container_name: base-cake-app-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_DEFAULT_LOCATE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_HOST=base-cake-app-db
      - DATABASE_USER=root
      - DATABASE_PASS=secret
      - DATABASE_NAME=pending
    command: bash -c "sh docker-init-setup.sh && apache2-foreground"
    ports:
      - "5000:80"
  db:
    container_name: base-cake-app-db
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d
      - ./Docker/mysql/data:/var/lib/mysql 
